# Dev configuration
server:
  port: 5000
security:
  basic:
    enabled: false
  ignored:
    - /**
management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss} %clr(%X{username}){magenta} - %clr(%c{10}[%L]){cyan} : %msg%n"
url:
  get_product_by_id: "http://localhost:3001/product/"
  get_product_similar_id: "http://localhost:3001/product/{productId}/similarids"
swagger:
  url:
    pom: "shared/springboot/integrator/pom.xml"

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 70
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 2
        waitDurationInOpenState: 2s
        slidingWindowType: COUNT_BASED
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 2000
      queryById:
        maxRetryAttempts: 3
        waitDuration: 2000
      findAll:
        maxRetryAttempts: 3
        waitDuration: 2000
  thread-pool-bulkhead:
    instances:
      productService:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 10
  ratelimiter:
    configs:
      productService:
        registerHealthIndicator: false
        limitForPeriod: 1
        limitRefreshPeriod: 2s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
  timelimiter:
    instances:
      productService:
        cancelRunningFuture: false
        timeoutDuration: 2s
